### ISSUE TITLE
Container module in rethinkdb example

### ISSUE THREAD

**Issue by justingreenberg** [js-data/js-data-examples#1]
Thank you for the hard work :) I think it would be awesome if the rethinkdb server and angular client examples worked with one another—ultimately is that your goal w/ this repo?

Is it possible to commit an example of the container module and associated config referenced in rethinkdb/app.js? `container.resolve()` seems to be responsible for creating the closure that bootstraps `app.js`...

```
var container = require('./container');
```

**Comment by jmdobry** [comment]
> Thank you for the hard work :)

Thanks, but I barely started on these examples. You're free to look, but there's a lot more to be done and it all needs to be documented.

> I think it would be awesome if the rethinkdb server and angular client examples worked with one another

They do, that's how I've been running the app. Things are a little hard-coded right now, but eventually you'll be able to plug and play examples via config. I haven't figured out how yet, but maybe something like `grunt start:angular-rethinkdb` or `grunt start:firebase-sql` to automatically start various combinations of the examples.

> Is it possible to commit an example of the container module and associated config

haha oops, like I said, I just barely started. That file didn't make it into the commit...

I will do a little more work on it right to make these initial examples more complete.

**Comment by justingreenberg** [comment]
Thanks for the quick reply—totally understand these are brand new. I like the idea of using grunt tasks. I'll put aside some time to contribute once I understand the `angular/rethinkdb` example architecture. It'd be great to see what the root `gruntfile.js` you're working with looks like also, if possible! Looking forward to it
